name: envify_generator
description: Code generator for envify, a better tool to handle environment variables.
version: 2.0.3
homepage: https://github.com/ajsultandev/envify_generator

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=5.12.0 <5.13.0"
  build: ^2.4.1
  dotenv: ^3.0.0
  envify: ^2.0.3
  path: ^1.8.3
  source_gen: ^1.4.0

dev_dependencies:
  lint: ^2.0.1
  source_gen_test: ^1.0.6
  test: ^1.24.0

scripts: ../derry.yaml
